// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNN8dpCCyB92Mq3uxdWxUJhfJAmMOwtf4',
    appId: '1:58322964727:android:1cf5321bd0c009925983f2',
    messagingSenderId: '58322964727',
    projectId: 'dark-panda-6fe35',
    databaseURL: 'https://dark-panda-6fe35.firebaseio.com',
    storageBucket: 'dark-panda-6fe35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjeIIffwXUdOd6K_srdIRmmB2fPZ57rhY',
    appId: '1:58322964727:ios:5afa705be9c6c74e5983f2',
    messagingSenderId: '58322964727',
    projectId: 'dark-panda-6fe35',
    databaseURL: 'https://dark-panda-6fe35.firebaseio.com',
    storageBucket: 'dark-panda-6fe35.appspot.com',
    iosClientId: '58322964727-sg74v44pfmk6r953mjastaddnhhrdsf4.apps.googleusercontent.com',
    iosBundleId: 'com.darkpanda.app',
  );
}
